# Site settings
title: "Journal Créatif en Vendée"
email: "comingsoon@gmail.com"
tel: "06 01 10 01 10"
description: "Organisation d'ateliers de journal créatifs en Vendée"  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
